# Generated by Django 4.0.1 on 2022-02-16 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user1', '0002_store'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='store',
            options={'default_permissions': ('add',), 'permissions': (('give_refund', 'Can refund customers'), ('can_hire', 'Can hire employees'), ('see_store', 'Customer See Store'))},
        ),
    ]
