# Generated by Django 4.0.1 on 2022-02-09 12:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_no', models.CharField(max_length=15, verbose_name='User Cell Number')),
                ('address', models.CharField(max_length=250, verbose_name='User Address')),
                ('dob', models.DateField(auto_now_add=True, verbose_name='User DOB')),
                ('user_pic', models.ImageField(upload_to='user_profile/%Y-%m-%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpeg', 'jpg', 'png'])])),
            ],
        ),
    ]
