# Generated by Django 4.0.1 on 2022-02-11 11:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_userprofile_email_userprofile_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('cat_id', models.AutoField(primary_key=True, serialize=False)),
                ('cname', models.CharField(max_length=150, null=True, verbose_name='Add Category Here')),
                ('at_updated', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False)),
                ('pname', models.CharField(max_length=150, verbose_name='Product Name')),
                ('ptitle', models.CharField(max_length=150, null=True, verbose_name='Product Title')),
                ('quantity', models.PositiveIntegerField(verbose_name='Product Quantity')),
                ('image', models.ImageField(default='avtar.png', upload_to='%Y-%m-%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpeg', 'jpg', 'png'])])),
                ('price', models.PositiveIntegerField(null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashb.category', verbose_name='Choose Category Here')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_quantity', models.PositiveIntegerField(verbose_name='Order Quantity')),
                ('date_of_oder', models.DateTimeField(default=django.utils.timezone.now)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashb.product', verbose_name='Product Name')),
                ('user', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='users.userprofile', verbose_name='User Name')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Order',
            },
        ),
    ]
