# Generated by Django 4.0.1 on 2022-02-21 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashb', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='date_of_oder',
            new_name='date_of_order',
        ),
    ]
