# Generated by Django 4.0.1 on 2022-02-21 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_feedback'),
        ('dashb', '0002_rename_date_of_oder_order_date_of_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='dashb.product', verbose_name='Product Name'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='users.userprofile', verbose_name='User Name'),
        ),
    ]
